Task 6.1: Combine year 2019 and year 2020’s crime records into one pandas dataframe. Drop duplicates as well as any record that has missing values in the following columns: “INCIDENT_NUMBER”, “OFFENSE_CODE”, “DISTRICT”, “Long”, “Lat”, “SHOOTING”, “OCCURRED_ON_DATE”. Save the “cleaned” pandas dataframe to a separate csv file.

In [47]:
import pandas as pd
Boston_crime_2019 = pd.read_csv("/Users/[editted]/Downloads/tmp9mkqyv6b.csv")
Boston_crime_2019.head()

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,102091671,2647,NaN,THREATS TO DO BODILY HARM,B3,417,0,2019-11-12 12:00:00,2019,11,Tuesday,12,NaN,MORA ST,42.282082,-71.073649,"(42.28208197671972, -71.07364874515646)"
1,102095489,3115,NaN,INVESTIGATE PERSON,E18,520,0,2019-11-25 16:30:00,2019,11,Monday,16,NaN,POYDRAS ST,42.256216,-71.124019,"(42.256215920402155, -71.12401947329023)"
2,102096818,2905,NaN,VAL - VIOLATION OF AUTO LAW,A1,,0,2019-11-30 21:00:00,2019,11,Saturday,21,NaN,SUDBURY ST & CAMBRIDGE ST\nBOSTON MA 02108\nU...,42.360866,-71.061316,"(42.360866027118476, -71.0613160019785)"
3,129092894,3201,NaN,PROPERTY - LOST/ MISSING,NaN,503,0,2019-11-16 13:30:00,2019,11,Saturday,13,NaN,AMERICAN LEGION HWY,42.284467,-71.111831,"(42.28446742674232, -71.11183088758158)"
4,129099920,3301,NaN,VERBAL DISPUTE,B2,330,0,2019-12-12 07:50:00,2019,12,Thursday,7,NaN,COLUMBIA ROAD,0.000000,0.000000,"(0, 0)"

In [48]:
Boston_crime_2020 = pd.read_csv("/Users/[editted]/Downloads/script_113631134_20210423193017_combine.csv")
Boston_crime_2020.head()

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,854652314,3115,NaN,INVESTIGATE PERSON,B2,289,0,2020-02-20 00:00:00,2020,2,Thursday,0,NaN,SCHROEDER PLZ,42.333679,-71.091878,"(42.3336792181085, -71.0918775461846)"
1,457856954,3115,NaN,INVESTIGATE PERSON,B2,289,0,2020-02-21 01:42:00,2020,2,Friday,1,NaN,SCHROEDER PLZ,42.333679,-71.091878,"(42.3336792181085, -71.0918775461846)"
2,302030654,1106,NaN,FRAUD - CREDIT CARD / ATM FRAUD,D4,167,0,2020-04-24 13:00:00,2020,4,Friday,13,NaN,MASSACHUSETTS AVE,42.339542,-71.069409,"(42.3395419898301, -71.0694087696754)"
3,212025777,1108,NaN,FRAUD - WELFARE,A7,28,0,2020-05-01 00:00:00,2020,5,Friday,0,NaN,TRENTON ST,42.370818,-71.039291,"(42.3708180467024, -71.0392907813515)"
4,212025557,2670,NaN,HARASSMENT/ CRIMINAL HARASSMENT,A1,77,0,2020-09-07 00:00:00,2020,9,Monday,0,NaN,PRINCE ST,42.361839,-71.059765,"(42.3618385665647, -71.0597648909416)"

In [49]:
Boston_crime_merged_data = Boston_crime_2019.append(Boston_crime_2020)
Boston_crime_merged_data.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,102091671,2647,NaN,THREATS TO DO BODILY HARM,B3,417,0,2019-11-12 12:00:00,2019,11,Tuesday,12,NaN,MORA ST,42.282082,-71.073649,"(42.28208197671972, -71.07364874515646)"
1,102095489,3115,NaN,INVESTIGATE PERSON,E18,520,0,2019-11-25 16:30:00,2019,11,Monday,16,NaN,POYDRAS ST,42.256216,-71.124019,"(42.256215920402155, -71.12401947329023)"
2,102096818,2905,NaN,VAL - VIOLATION OF AUTO LAW,A1,,0,2019-11-30 21:00:00,2019,11,Saturday,21,NaN,SUDBURY ST & CAMBRIDGE ST\nBOSTON MA 02108\nU...,42.360866,-71.061316,"(42.360866027118476, -71.0613160019785)"
3,129092894,3201,NaN,PROPERTY - LOST/ MISSING,NaN,503,0,2019-11-16 13:30:00,2019,11,Saturday,13,NaN,AMERICAN LEGION HWY,42.284467,-71.111831,"(42.28446742674232, -71.11183088758158)"
4,129099920,3301,NaN,VERBAL DISPUTE,B2,330,0,2019-12-12 07:50:00,2019,12,Thursday,7,NaN,COLUMBIA ROAD,0.000000,0.000000,"(0, 0)"

In [50]:
Boston_crime_merged_data.drop_duplicates()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,102091671,2647,NaN,THREATS TO DO BODILY HARM,B3,417,0,2019-11-12 12:00:00,2019,11,Tuesday,12,NaN,MORA ST,42.282082,-71.073649,"(42.28208197671972, -71.07364874515646)"
1,102095489,3115,NaN,INVESTIGATE PERSON,E18,520,0,2019-11-25 16:30:00,2019,11,Monday,16,NaN,POYDRAS ST,42.256216,-71.124019,"(42.256215920402155, -71.12401947329023)"
2,102096818,2905,NaN,VAL - VIOLATION OF AUTO LAW,A1,,0,2019-11-30 21:00:00,2019,11,Saturday,21,NaN,SUDBURY ST & CAMBRIDGE ST\nBOSTON MA 02108\nU...,42.360866,-71.061316,"(42.360866027118476, -71.0613160019785)"
3,129092894,3201,NaN,PROPERTY - LOST/ MISSING,NaN,503,0,2019-11-16 13:30:00,2019,11,Saturday,13,NaN,AMERICAN LEGION HWY,42.284467,-71.111831,"(42.28446742674232, -71.11183088758158)"
4,129099920,3301,NaN,VERBAL DISPUTE,B2,330,0,2019-12-12 07:50:00,2019,12,Thursday,7,NaN,COLUMBIA ROAD,0.000000,0.000000,"(0, 0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70889,20063425,3114,NaN,INVESTIGATE PROPERTY,A7,21,0,2020-09-01 00:00:00,2020,9,Tuesday,0,NaN,PARIS ST,42.374427,-71.035279,"(42.3744269722053, -71.0352787630199)"
70890,20062356,1107,NaN,FRAUD - IMPERSONATION,E18,520,0,2020-08-28 18:39:00,2020,8,Friday,18,NaN,RIVERSIDE SQ,42.256216,-71.124019,"(42.2562159204022, -71.1240194732902)"
70891,20046400,1501,NaN,WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...,B2,330,0,2020-07-02 01:38:00,2020,7,Thursday,1,NaN,PASADENA RD,42.305761,-71.083772,"(42.3057609263196, -71.0837715727385)"
70892,20038446,1501,NaN,WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...,B2,300,0,2020-06-03 01:15:00,2020,6,Wednesday,1,NaN,WASHINGTON ST,42.323808,-71.089150,"(42.3238077563779, -71.0891502345332)"
70893,20030892,540,NaN,BURGLARY - COMMERICAL,C11,380,0,2020-05-03 00:00:00,2020,5,Sunday,0,NaN,GALLIVAN BLVD,42.283700,-71.047761,"(42.2837003080534, -71.0477614298657)"

In [51]:
Boston_crime_merged_dropped = Boston_crime_merged_data.dropna(subset=['INCIDENT_NUMBER', 'OFFENSE_CODE', 'DISTRICT', 'Long', 'Lat', 'SHOOTING', 'OCCURRED_ON_DATE'])
Boston_crime_merged_dropped.to_csv("/Users/[editted]/Downloads/boston_crime.csv")

Task 6.2: Read the csv file generated from Task 6.1 as a pandas dataframe. Use functions inside pandas to create a frequency table that counts the total number of crime incidents in Boston in each month from 2019 to 2020. Print this table.

In [52]:
boston_crime = pd.read_csv("/Users/[editted]/Downloads/boston_crime.csv")

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [59]:
freq_table = boston_crime.groupby(['MONTH', 'YEAR']).count()
print(freq_table)

            Unnamed: 0  INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
MONTH YEAR
1     2019        6933             6933          6933                   0
      2020        6318             6318          6318                   0
2     2019        6147             6147          6147                   0
      2020        5874             5874          5874                   0
3     2019        7065             7065          7065                   0
      2020        5490             5490          5490                   0
4     2019        6936             6936          6936                   0
      2020        4362             4362          4362                   0
5     2019        7763             7763          7763                   0
      2020        5411             5411          5411                   0
6     2019        7597             7597          7597                   0
      2020        5897             5897          5897                   0
7     2019        8036             8036          8036                   0
      2020        6213             6213          6213                   0
8     2019        8379             8379          8379                   0
      2020        6507             6507          6507                   0
9     2019        8133             8133          8133                   0
      2020        6467             6467          6467                   0
10    2019        6990             6990          6990                   0
      2020        6741             6741          6741                   0
11    2019        6338             6338          6338                   0
      2020        5755             5755          5755                   0
12    2019        5826             5826          5826                   0
      2020        5581             5581          5581                   0

            OFFENSE_DESCRIPTION  DISTRICT  REPORTING_AREA  SHOOTING  \
MONTH YEAR
1     2019                 6933      6933            6933      6933
      2020                 6318      6318            6318      6318
2     2019                 6147      6147            6147      6147
      2020                 5874      5874            5874      5874
3     2019                 7065      7065            7065      7065
      2020                 5490      5490            5490      5490
4     2019                 6936      6936            6936      6936
      2020                 4362      4362            4362      4362
5     2019                 7763      7763            7763      7763
      2020                 5411      5411            5411      5411
6     2019                 7597      7597            7597      7597
      2020                 5897      5897            5897      5897
7     2019                 8036      8036            8036      8036
      2020                 6213      6213            6213      6213
8     2019                 8379      8379            8379      8379
      2020                 6507      6507            6507      6507
9     2019                 8133      8133            8133      8133
      2020                 6467      6467            6467      6467
10    2019                 6990      6990            6990      6990
      2020                 6741      6741            6741      6741
11    2019                 6338      6338            6338      6338
      2020                 5755      5755            5755      5755
12    2019                 5826      5826            5826      5826
      2020                 5581      5581            5581      5581

            OCCURRED_ON_DATE  DAY_OF_WEEK  HOUR  UCR_PART  STREET   Lat  Long  \
MONTH YEAR
1     2019              6933         6933  6933         0    6933  6933  6933
      2020              6318         6318  6318         0    6318  6318  6318
2     2019              6147         6147  6147         0    6147  6147  6147
      2020              5874         5874  5874         0    5874  5874  5874
3     2019              7065         7065  7065         0    7065  7065  7065
      2020              5490         5490  5490         0    5490  5490  5490
4     2019              6936         6936  6936         0    6936  6936  6936
      2020              4362         4362  4362         0    4362  4362  4362
5     2019              7763         7763  7763         0    7763  7763  7763
      2020              5411         5411  5411         0    5411  5411  5411
6     2019              7597         7597  7597         0    7597  7597  7597
      2020              5897         5897  5897         0    5897  5897  5897
7     2019              8036         8036  8036         0    8036  8036  8036
      2020              6213         6213  6213         0    6213  6213  6213
8     2019              8379         8379  8379         0    8379  8379  8379
      2020              6507         6507  6507         0    6507  6507  6507
9     2019              8133         8133  8133         0    8133  8133  8133
      2020              6467         6467  6467         0    6467  6467  6467
10    2019              6990         6990  6990         0    6990  6990  6990
      2020              6741         6741  6741         0    6741  6741  6741
11    2019              6338         6338  6338         0    6338  6338  6338
      2020              5755         5755  5755         0    5755  5755  5755
12    2019              5826         5826  5826         0    5826  5826  5826
      2020              5581         5581  5581         0    5581  5581  5581

            Location
MONTH YEAR
1     2019      6933
      2020      6318
2     2019      6147
      2020      5874
3     2019      7065
      2020      5490
4     2019      6936
      2020      4362
5     2019      7763
      2020      5411
6     2019      7597
      2020      5897
7     2019      8036
      2020      6213
8     2019      8379
      2020      6507
9     2019      8133
      2020      6467
10    2019      6990
      2020      6741
11    2019      6338
      2020      5755
12    2019      5826
      2020      5581

Task 6.3: Count the total number of crime incidents in each year by district (column “DISTRICT” in the data). Ignore DISTRACT with null value as well as value  “External”. Discuss the spatial distribution of crime. Do you see any significant difference between districts in terms of their crime counts?

In [60]:
district_freq_table = boston_crime.groupby(['MONTH', 'YEAR', 'DISTRICT']).count()
print(freq_table)

            Unnamed: 0  INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
MONTH YEAR
1     2019        6933             6933          6933                   0
      2020        6318             6318          6318                   0
2     2019        6147             6147          6147                   0
      2020        5874             5874          5874                   0
3     2019        7065             7065          7065                   0
      2020        5490             5490          5490                   0
4     2019        6936             6936          6936                   0
      2020        4362             4362          4362                   0
5     2019        7763             7763          7763                   0
      2020        5411             5411          5411                   0
6     2019        7597             7597          7597                   0
      2020        5897             5897          5897                   0
7     2019        8036             8036          8036                   0
      2020        6213             6213          6213                   0
8     2019        8379             8379          8379                   0
      2020        6507             6507          6507                   0
9     2019        8133             8133          8133                   0
      2020        6467             6467          6467                   0
10    2019        6990             6990          6990                   0
      2020        6741             6741          6741                   0
11    2019        6338             6338          6338                   0
      2020        5755             5755          5755                   0
12    2019        5826             5826          5826                   0
      2020        5581             5581          5581                   0

            OFFENSE_DESCRIPTION  DISTRICT  REPORTING_AREA  SHOOTING  \
MONTH YEAR
1     2019                 6933      6933            6933      6933
      2020                 6318      6318            6318      6318
2     2019                 6147      6147            6147      6147
      2020                 5874      5874            5874      5874
3     2019                 7065      7065            7065      7065
      2020                 5490      5490            5490      5490
4     2019                 6936      6936            6936      6936
      2020                 4362      4362            4362      4362
5     2019                 7763      7763            7763      7763
      2020                 5411      5411            5411      5411
6     2019                 7597      7597            7597      7597
      2020                 5897      5897            5897      5897
7     2019                 8036      8036            8036      8036
      2020                 6213      6213            6213      6213
8     2019                 8379      8379            8379      8379
      2020                 6507      6507            6507      6507
9     2019                 8133      8133            8133      8133
      2020                 6467      6467            6467      6467
10    2019                 6990      6990            6990      6990
      2020                 6741      6741            6741      6741
11    2019                 6338      6338            6338      6338
      2020                 5755      5755            5755      5755
12    2019                 5826      5826            5826      5826
      2020                 5581      5581            5581      5581

            OCCURRED_ON_DATE  DAY_OF_WEEK  HOUR  UCR_PART  STREET   Lat  Long  \
MONTH YEAR
1     2019              6933         6933  6933         0    6933  6933  6933
      2020              6318         6318  6318         0    6318  6318  6318
2     2019              6147         6147  6147         0    6147  6147  6147
      2020              5874         5874  5874         0    5874  5874  5874
3     2019              7065         7065  7065         0    7065  7065  7065
      2020              5490         5490  5490         0    5490  5490  5490
4     2019              6936         6936  6936         0    6936  6936  6936
      2020              4362         4362  4362         0    4362  4362  4362
5     2019              7763         7763  7763         0    7763  7763  7763
      2020              5411         5411  5411         0    5411  5411  5411
6     2019              7597         7597  7597         0    7597  7597  7597
      2020              5897         5897  5897         0    5897  5897  5897
7     2019              8036         8036  8036         0    8036  8036  8036
      2020              6213         6213  6213         0    6213  6213  6213
8     2019              8379         8379  8379         0    8379  8379  8379
      2020              6507         6507  6507         0    6507  6507  6507
9     2019              8133         8133  8133         0    8133  8133  8133
      2020              6467         6467  6467         0    6467  6467  6467
10    2019              6990         6990  6990         0    6990  6990  6990
      2020              6741         6741  6741         0    6741  6741  6741
11    2019              6338         6338  6338         0    6338  6338  6338
      2020              5755         5755  5755         0    5755  5755  5755
12    2019              5826         5826  5826         0    5826  5826  5826
      2020              5581         5581  5581         0    5581  5581  5581

            Location
MONTH YEAR
1     2019      6933
      2020      6318
2     2019      6147
      2020      5874
3     2019      7065
      2020      5490
4     2019      6936
      2020      4362
5     2019      7763
      2020      5411
6     2019      7597
      2020      5897
7     2019      8036
      2020      6213
8     2019      8379
      2020      6507
9     2019      8133
      2020      6467
10    2019      6990
      2020      6741
11    2019      6338
      2020      5755
12    2019      5826
      2020      5581