6.1

In [77]:
import pandas as pd
import glob
import os
import numpy as np

In [9]:
files = os.path.join('/Users/[editted]/Documents/Boston_Crime', '*.csv' )
files = glob.glob(files)
df = pd.concat(map(pd.read_csv, files), ignore_index = True)
print(df)

/var/folders/r8/83_dlqf14nn0b3855_ng_wsh0000gn/T/ipykernel_72895/2273255238.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat(map(pd.read_csv, files), ignore_index = True)

       INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0            102091671          2647                 NaN
1            102095489          3115                 NaN
2            102096818          2905                 NaN
3            129092894          3201                 NaN
4            129099920          3301                 NaN
...                ...           ...                 ...
158073        20063425          3114                 NaN
158074        20062356          1107                 NaN
158075        20046400          1501                 NaN
158076        20038446          1501                 NaN
158077        20030892           540                 NaN

                                      OFFENSE_DESCRIPTION DISTRICT  \
0                               THREATS TO DO BODILY HARM       B3
1                                      INVESTIGATE PERSON      E18
2                             VAL - VIOLATION OF AUTO LAW       A1
3                                PROPERTY - LOST/ MISSING      NaN
4                                          VERBAL DISPUTE       B2
...                                                   ...      ...
158073                               INVESTIGATE PROPERTY       A7
158074                              FRAUD - IMPERSONATION      E18
158075  WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...       B2
158076  WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...       B2
158077                              BURGLARY - COMMERICAL      C11

       REPORTING_AREA  SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  \
0                 417         0  2019-11-12 12:00:00  2019     11     Tuesday
1                 520         0  2019-11-25 16:30:00  2019     11      Monday
2                             0  2019-11-30 21:00:00  2019     11    Saturday
3                 503         0  2019-11-16 13:30:00  2019     11    Saturday
4                 330         0  2019-12-12 07:50:00  2019     12    Thursday
...               ...       ...                  ...   ...    ...         ...
158073             21         0  2020-09-01 00:00:00  2020      9     Tuesday
158074            520         0  2020-08-28 18:39:00  2020      8      Friday
158075            330         0  2020-07-02 01:38:00  2020      7    Thursday
158076            300         0  2020-06-03 01:15:00  2020      6   Wednesday
158077            380         0  2020-05-03 00:00:00  2020      5      Sunday

        HOUR  UCR_PART                                             STREET  \
0         12       NaN                                            MORA ST
1         16       NaN                                         POYDRAS ST
2         21       NaN  SUDBURY ST & CAMBRIDGE ST\nBOSTON  MA 02108\nU...
3         13       NaN                                AMERICAN LEGION HWY
4          7       NaN                                      COLUMBIA ROAD
...      ...       ...                                                ...
158073     0       NaN                                           PARIS ST
158074    18       NaN                                       RIVERSIDE SQ
158075     1       NaN                                        PASADENA RD
158076     1       NaN                                      WASHINGTON ST
158077     0       NaN                                      GALLIVAN BLVD

              Lat       Long                                  Location
0       42.282082 -71.073649   (42.28208197671972, -71.07364874515646)
1       42.256216 -71.124019  (42.256215920402155, -71.12401947329023)
2       42.360866 -71.061316   (42.360866027118476, -71.0613160019785)
3       42.284467 -71.111831   (42.28446742674232, -71.11183088758158)
4        0.000000   0.000000                                    (0, 0)
...           ...        ...                                       ...
158073  42.374427 -71.035279     (42.3744269722053, -71.0352787630199)
158074  42.256216 -71.124019     (42.2562159204022, -71.1240194732902)
158075  42.305761 -71.083772     (42.3057609263196, -71.0837715727385)
158076  42.323808 -71.089150     (42.3238077563779, -71.0891502345332)
158077  42.283700 -71.047761     (42.2837003080534, -71.0477614298657)

[158078 rows x 17 columns]

/var/folders/r8/83_dlqf14nn0b3855_ng_wsh0000gn/T/ipykernel_72895/2273255238.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat(map(pd.read_csv, files), ignore_index = True)

In [10]:
df.drop_duplicates()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,102091671,2647,NaN,THREATS TO DO BODILY HARM,B3,417,0,2019-11-12 12:00:00,2019,11,Tuesday,12,NaN,MORA ST,42.282082,-71.073649,"(42.28208197671972, -71.07364874515646)"
1,102095489,3115,NaN,INVESTIGATE PERSON,E18,520,0,2019-11-25 16:30:00,2019,11,Monday,16,NaN,POYDRAS ST,42.256216,-71.124019,"(42.256215920402155, -71.12401947329023)"
2,102096818,2905,NaN,VAL - VIOLATION OF AUTO LAW,A1,,0,2019-11-30 21:00:00,2019,11,Saturday,21,NaN,SUDBURY ST & CAMBRIDGE ST\nBOSTON MA 02108\nU...,42.360866,-71.061316,"(42.360866027118476, -71.0613160019785)"
3,129092894,3201,NaN,PROPERTY - LOST/ MISSING,NaN,503,0,2019-11-16 13:30:00,2019,11,Saturday,13,NaN,AMERICAN LEGION HWY,42.284467,-71.111831,"(42.28446742674232, -71.11183088758158)"
4,129099920,3301,NaN,VERBAL DISPUTE,B2,330,0,2019-12-12 07:50:00,2019,12,Thursday,7,NaN,COLUMBIA ROAD,0.000000,0.000000,"(0, 0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158073,20063425,3114,NaN,INVESTIGATE PROPERTY,A7,21,0,2020-09-01 00:00:00,2020,9,Tuesday,0,NaN,PARIS ST,42.374427,-71.035279,"(42.3744269722053, -71.0352787630199)"
158074,20062356,1107,NaN,FRAUD - IMPERSONATION,E18,520,0,2020-08-28 18:39:00,2020,8,Friday,18,NaN,RIVERSIDE SQ,42.256216,-71.124019,"(42.2562159204022, -71.1240194732902)"
158075,20046400,1501,NaN,WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...,B2,330,0,2020-07-02 01:38:00,2020,7,Thursday,1,NaN,PASADENA RD,42.305761,-71.083772,"(42.3057609263196, -71.0837715727385)"
158076,20038446,1501,NaN,WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...,B2,300,0,2020-06-03 01:15:00,2020,6,Wednesday,1,NaN,WASHINGTON ST,42.323808,-71.089150,"(42.3238077563779, -71.0891502345332)"
158077,20030892,540,NaN,BURGLARY - COMMERICAL,C11,380,0,2020-05-03 00:00:00,2020,5,Sunday,0,NaN,GALLIVAN BLVD,42.283700,-71.047761,"(42.2837003080534, -71.0477614298657)"

In [11]:
print(df.dropna(axis = 1))

       INCIDENT_NUMBER  OFFENSE_CODE  \
0            102091671          2647
1            102095489          3115
2            102096818          2905
3            129092894          3201
4            129099920          3301
...                ...           ...
158073        20063425          3114
158074        20062356          1107
158075        20046400          1501
158076        20038446          1501
158077        20030892           540

                                      OFFENSE_DESCRIPTION REPORTING_AREA  \
0                               THREATS TO DO BODILY HARM            417
1                                      INVESTIGATE PERSON            520
2                             VAL - VIOLATION OF AUTO LAW
3                                PROPERTY - LOST/ MISSING            503
4                                          VERBAL DISPUTE            330
...                                                   ...            ...
158073                               INVESTIGATE PROPERTY             21
158074                              FRAUD - IMPERSONATION            520
158075  WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...            330
158076  WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...            300
158077                              BURGLARY - COMMERICAL            380

        SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  \
0              0  2019-11-12 12:00:00  2019     11     Tuesday    12
1              0  2019-11-25 16:30:00  2019     11      Monday    16
2              0  2019-11-30 21:00:00  2019     11    Saturday    21
3              0  2019-11-16 13:30:00  2019     11    Saturday    13
4              0  2019-12-12 07:50:00  2019     12    Thursday     7
...          ...                  ...   ...    ...         ...   ...
158073         0  2020-09-01 00:00:00  2020      9     Tuesday     0
158074         0  2020-08-28 18:39:00  2020      8      Friday    18
158075         0  2020-07-02 01:38:00  2020      7    Thursday     1
158076         0  2020-06-03 01:15:00  2020      6   Wednesday     1
158077         0  2020-05-03 00:00:00  2020      5      Sunday     0

              Lat       Long                                  Location
0       42.282082 -71.073649   (42.28208197671972, -71.07364874515646)
1       42.256216 -71.124019  (42.256215920402155, -71.12401947329023)
2       42.360866 -71.061316   (42.360866027118476, -71.0613160019785)
3       42.284467 -71.111831   (42.28446742674232, -71.11183088758158)
4        0.000000   0.000000                                    (0, 0)
...           ...        ...                                       ...
158073  42.374427 -71.035279     (42.3744269722053, -71.0352787630199)
158074  42.256216 -71.124019     (42.2562159204022, -71.1240194732902)
158075  42.305761 -71.083772     (42.3057609263196, -71.0837715727385)
158076  42.323808 -71.089150     (42.3238077563779, -71.0891502345332)
158077  42.283700 -71.047761     (42.2837003080534, -71.0477614298657)

[158078 rows x 13 columns]

In [78]:
df.to_csv('cleaned.csv')

6.2

In [79]:
cb_df = pd.read_csv('cleaned.csv')
print(cb_df)

        Unnamed: 0 INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0                0       102091671          2647                 NaN
1                1       102095489          3115                 NaN
2                2       102096818          2905                 NaN
3                3       129092894          3201                 NaN
4                4       129099920          3301                 NaN
...            ...             ...           ...                 ...
158073      158073        20063425          3114                 NaN
158074      158074        20062356          1107                 NaN
158075      158075        20046400          1501                 NaN
158076      158076        20038446          1501                 NaN
158077      158077        20030892           540                 NaN

                                      OFFENSE_DESCRIPTION DISTRICT  \
0                               THREATS TO DO BODILY HARM       B3
1                                      INVESTIGATE PERSON      E18
2                             VAL - VIOLATION OF AUTO LAW       A1
3                                PROPERTY - LOST/ MISSING      NaN
4                                          VERBAL DISPUTE       B2
...                                                   ...      ...
158073                               INVESTIGATE PROPERTY       A7
158074                              FRAUD - IMPERSONATION      E18
158075  WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...       B2
158076  WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TR...       B2
158077                              BURGLARY - COMMERICAL      C11

       REPORTING_AREA  SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  \
0                 417         0  2019-11-12 12:00:00  2019     11     Tuesday
1                 520         0  2019-11-25 16:30:00  2019     11      Monday
2                             0  2019-11-30 21:00:00  2019     11    Saturday
3                 503         0  2019-11-16 13:30:00  2019     11    Saturday
4                 330         0  2019-12-12 07:50:00  2019     12    Thursday
...               ...       ...                  ...   ...    ...         ...
158073             21         0  2020-09-01 00:00:00  2020      9     Tuesday
158074            520         0  2020-08-28 18:39:00  2020      8      Friday
158075            330         0  2020-07-02 01:38:00  2020      7    Thursday
158076            300         0  2020-06-03 01:15:00  2020      6   Wednesday
158077            380         0  2020-05-03 00:00:00  2020      5      Sunday

        HOUR  UCR_PART                                             STREET  \
0         12       NaN                                            MORA ST
1         16       NaN                                         POYDRAS ST
2         21       NaN  SUDBURY ST & CAMBRIDGE ST\nBOSTON  MA 02108\nU...
3         13       NaN                                AMERICAN LEGION HWY
4          7       NaN                                      COLUMBIA ROAD
...      ...       ...                                                ...
158073     0       NaN                                           PARIS ST
158074    18       NaN                                       RIVERSIDE SQ
158075     1       NaN                                        PASADENA RD
158076     1       NaN                                      WASHINGTON ST
158077     0       NaN                                      GALLIVAN BLVD

              Lat       Long                                  Location
0       42.282082 -71.073649   (42.28208197671972, -71.07364874515646)
1       42.256216 -71.124019  (42.256215920402155, -71.12401947329023)
2       42.360866 -71.061316   (42.360866027118476, -71.0613160019785)
3       42.284467 -71.111831   (42.28446742674232, -71.11183088758158)
4        0.000000   0.000000                                    (0, 0)
...           ...        ...                                       ...
158073  42.374427 -71.035279     (42.3744269722053, -71.0352787630199)
158074  42.256216 -71.124019     (42.2562159204022, -71.1240194732902)
158075  42.305761 -71.083772     (42.3057609263196, -71.0837715727385)
158076  42.323808 -71.089150     (42.3238077563779, -71.0891502345332)
158077  42.283700 -71.047761     (42.2837003080534, -71.0477614298657)

[158078 rows x 18 columns]

/var/folders/r8/83_dlqf14nn0b3855_ng_wsh0000gn/T/ipykernel_72895/1963667786.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  cb_df = pd.read_csv('cleaned.csv')

In [86]:
YM_table = pd.crosstab(index = cb_df['MONTH'], columns = cb_df['YEAR'])
YM_table

YEAR   2019  2020
MONTH
1      6958  6342
2      6173  5897
3      7093  5513
4      6963  4387
5      7783  5439
6      7635  5925
7      8083  6236
8      8430  6533
9      8184  6484
10     7121  6766
11     6468  5770
12     6293  5602

6.3

In [106]:
pd.crosstab(index = cb_df['DISTRICT'], columns = cb_df['YEAR'])

YEAR       2019   2020
DISTRICT
A1         9936   7013
A15        1889   1600
A7         3400   3141
B2        13030  10442
B3         9591   7828
C11       11022   8992
C6         6286   5440
D14        5704   4756
D4        11276   9283
E13        4928   4103
E18        5197   4177
E5         3807   3595
External     77    246

The district B2 is obviously had more incident cases than other ditricts, and we can also see the incidents abated from 2019 to 2020, so we can say that the security was enhanced through the years. Meanwhile, A15 has the least cases during two years, but we cannot know the deep reason of it (acreage or security).